### ISSUE TITLE
Print action not working

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#18]
Nothing happens when tapping the print button in the menu for a plan

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/bc36c10e1fc3af41befd2cd4b7b3342563c56e9c, https://github.com/overlevelsesguiden/The10H-Android/commit/6802dc30009c921f415a6968f5896b520a05bbbc & https://github.com/overlevelsesguiden/The10H-Android/commit/a3cca2305b788b440d70ccb1059a247869fb1b31
